### PR TITLE
Feature 9 Tile Entities changes

### PR DESCRIPTION
**Pull request by Youssefb1234**
…dTile and UtilityTile.

### CODE REVIEW

**Review by alirezazim03 — APPROVED** [review]

**Review by iamyanbo — CHANGES_REQUESTED** [review]
action methods must handle subtracting and adding money from player to player

**Review by TahirLeonenko — CHANGES_REQUESTED** [review]
ColorPropertyTile needs a house and hotel attributes that keeps track of how many houses and hotels have been built on the property. I'll also need getter methods for both of those attributes

**Review by TahirLeonenko — CHANGES_REQUESTED** [review]
Also, you need to implement the getRent method. Also for the getRent method you will need to check whether the property has houses/hotels on it, and to give back the amount of rent needed based on the amount of hotels/houses. If there are no houses/hotels, you'll need to check whether the player owns the other properties of the same colour. This is because if the player owns all the properties of the same colour, the rent of an unimproved property doubles.

**Review by TahirLeonenko — CHANGES_REQUESTED** [review]
Also, the action method only returns a TileActionResultModel. The action method also needs to implement what actually happens when they land on the tile (buying/paying rent)

**Review by iamyanbo — APPROVED** [review]

**Review by colewiltse — APPROVED** [review]

**Review by alirezazim03 — APPROVED** [review]

**Review by TahirLeonenko — APPROVED** [review]

**Pull request merged**
